Server side cookie generation and validation
solana-labs/solana-payments-app pull request #18
Opened 2023-04-26 18:09 UTC by harshasomisetty

2023-04-26 18:32 UTC, nramadas requested changes

2023-04-26 18:32 UTC, nramadas commented on apps/merchant-ui/src/components/ShopifySignIn.tsx
> +      userId: userId,
you don't need this in this call. The cookie already tells the backend who the user is. In fact, for any sort of `/me` type identity call, the server should _not_ rely on the client to tell it who the user is, since the client can lie.

2023-04-26 21:33 UTC, harshasomisetty commented on apps/merchant-ui/src/components/ShopifySignIn.tsx
> +      userId: userId,
Yeah good point defeats the whole purpose of the cookie and pretty unsafe. Changed to the signed authentication code, the server now has the secret key to decode to get user-id.


There probably should be a safe way to store the secret-key now though, right?

2023-04-27 01:13 UTC, littlejohntj commented on apps/merchant-ui/src/components/ShopifySignIn.tsx
> +      userId: userId,
yeah vercel handles secret management and we can store in .env.local for local development.

you can access it then via:

`process.env.JWT_SECRET_KEY`

2023-04-27 22:06 UTC, nramadas commented on apps/merchant-ui/src/pages/api/me.ts
> +const validateToken = (req: NextApiRequest): boolean => {
I would consider turning this into a higher-order function. Something like this:

```ts
export interface AuthenticatedNextApiRequest extends NextApiRequest {
  userId: string;
}

export const withAuth = (fn: (req: AuthenticatedNextApiRequest, res: NextApiResponse) => void) => {
  return (req: NextApiRequest, res: NextApiResponse) => {
    const authCookie = req.cookies["authToken"];

    if (!authCookie) {
      res.status(401).send("Unauthorized");
      return;
    }

    try {
      const { userId } = jwt.verify(authCookie, process.env.JWT_SECRET_KEY);
      return fn({ ...req, userId }, res);
    } catch {
      res.status(401).send("Unauthorized");
    }
  };
};
```

What's nice about this is that now it becomes really easy to create a handler that needs auth:
```ts
export default withAuth(function handler(req: AuthenticatedNextApiRequest, res: NextApiResponse) {
  const userId = req.userId;

  // do stuff with user
}));
```

2023-04-27 22:06 UTC, nramadas commented on apps/merchant-ui/src/pages/api/mockcookie.ts
> +  res.setHeader(
instead of setting a header of `set-cookie`, i think you should just be able to:

```ts
res.cookie('authToken', token, cookieOptions);
```

I would avoid trying to string parse/manipulate headers; it's easy to mess things up

2023-04-28 18:47 UTC, harshasomisetty commented on apps/merchant-ui/src/pages/api/mockcookie.ts
> +  res.setHeader(
I think res.cookie is only part of express and not the NextApiRequest object.

I think we're changing to a seperate express server soon, so i'll make this change there

2023-05-13 03:12 UTC, merged